databricks:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: sujeet_data_analytics_workspace
      schema: bronze_dev
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      threads: 4
    prod:
      type: databricks
      catalog: sujeet_data_analytics_workspace
      schema: bronze_prod
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      threads: 4
