look_dbt:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: sujeet_data_analytics_workspace
      schema: analytics_dev
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 8
