look_dbt:                          # MUST match dbt_project.yml: profile: 'look_dbt'
  target: dev
  outputs:
    dev:
      type: databricks           
      catalog: sujeet_data_analytics_workspace
      schema: default        # your personal dev schema (overridden by model configs at build time)
      host: "dbc-ee865a03-4133.cloud.databricks.com"      
      http_path: "/sql/1.0/warehouses/cc8e8799ab989b19"
      token: "dapie1dc103e34e3d8266d7ea730bf492c19"
      threads: 8
